backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Blog Posts
    folder: posts
    create: true
    fields:
      - { name: tags, label: Tags, widget: list, required: false }
      - { name: published, label: Published, widget: boolean }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }